k8s:
  namespace: to_define

helm:
  repo_name: trino
  repo_url: https://trinodb.github.io/charts
  chart_name: trino
  release_name: trino_release

values_files:
  # Path where jinja template is rendered
  tmp_path: /tmp/trino_values.yaml

  # You must update the catalog name through the key "your_catalog_name"
  catalogs:
    your_catalog_name: |
      connector.name=iceberg
      iceberg.catalog.type=rest
      iceberg.rest-catalog.uri=https://polaris-catalog.lab.incubateur.finances.rie.gouv.fr/api/catalog
      iceberg.rest-catalog.oauth2.server-uri=https://polaris-catalog.lab.incubateur.finances.rie.gouv.fr/api/catalog/v1/oauth/tokens
      iceberg.rest-catalog.warehouse=data_store
      iceberg.rest-catalog.security=OAUTH2
      iceberg.rest-catalog.oauth2.credential=client_id:client_secret
      iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL
      iceberg.rest-catalog.nested-namespace-enabled=true
      iceberg.rest-catalog.vended-credentials-enabled=false
      fs.native-s3.enabled=true
      s3.endpoint=https://minio.lab.incubateur.finances.rie.gouv.fr
      s3.region=us-east-1
      s3.aws-access-key=access-key
      s3.aws-secret-key=secret-key
      s3.path-style-access=true

  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: your_host.lab.incubateur.finances.rie.gouv.fr
        paths:
          - path: /
            pathType: ImplementationSpecific
